---
title: "Longitudinal Analysis"
format: revealjs
editor: visual
---

```{r echo=FALSE}
# Load necessary libraries
library(labelled)   # labeling data
library(rstatix)    # summary statistics
library(ggpubr)     # convenient summary statistics and plots
library(GGally)     # advanced plots
library(car)        # useful for ANOVA/Wald tests
library(Epi)        # easy CI for model coefficients/predictions
library(lme4)       # linear mixed-effects models
library(lmerTest)   # tests for linear mixed-effects models
library(emmeans)    # marginal means
library(multcomp)   # CI for linear combinations of model coefficients
library(geepack)    # generalized estimating equations
library(ggeffects)  # marginal effects, adjusted predictions
library(gt)         # nice tables
library(tidyverse)  # for data manipulation, visualization, and more
library(readr)      # to read CSV files
library(nlme)       # for mixed-effects models
library(reshape2)   # data reshaping
library(ggplot2)    # for data visualization
library(tidyr)      # for tidying data
library(dplyr)      # data manipulation
library(kableExtra) # enhanced tables
library(corrplot)   # for correlation matrix visualization
library(joineR)     # joint modeling of longitudinal and survival data
library(MASS)       # for statistical functions
library(lattice)    # for trellis graphics
library(gtsummary)  # for summary tables

# Set the theme for ggplot
theme_set(theme_minimal() + theme(legend.position = "bottom"))

# Load the data
actg <- read_csv("actg193a (1).csv")
```

## Introduction

## Project Goal

## Scientific Objectives

## Data Description

## Methods

-   Exploratory Data Analysis

-   Statistical Analysis

## Results
```{r echo=FALSE}
head(actg)
actg_new<-actg|>mutate_at(vars(sex, trt), as.factor)|>mutate_at(vars(week, age), as.integer)

actg_new$sex<-factor(actg_new$sex, levels = c("1", "0"), labels = c("M", "F"))
actg_new$trt <- factor(actg_new$trt, 
                   levels = c(1, 2, 3, 4), 
                   labels = c("Zidovudine+AltDid", "Zidovudine+Zalcit", "Zidovudine+Did", "Zidovudine+Did+Nev"))

head(actg_new)
```
```{r echo=FALSE}

```

## Discussion

## Appendix
